exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1        # You Must Have A Polkit
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP # For XDPH
exec-once = dbus-update-activation-environment --systemd --all # For XDPH
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP # For XDPH

exec-once = waybar # Status Bar
exec-once = $HOME/.config/hypr/hyprdesktop # Ensure Proper Portals Are Loaded
exec-once = mako  # Notifications
exec-once = hyprpaper # Wallpaper Daemon
exec-once = nm-applet --indicator


#exec-once = wl-clipboard-history -t # Clipboard
#exec-once = thunar --daemon # File Managers Daemon
#exec-once = hyprctl setcursor Bibata-Modern-Ice 32 # Set Proper Curser & Size
